---
abstract: 'A tool for routing paths'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  Test::Builder: 0
  Test::Deep: 0
  Test::Exception: 0.21
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Path-Router
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec::Unix: 0
  Moose: 0.46
version: 0.03
