---
abstract: 'A tool for routing paths'
author:
  - 'Stevan Little <stevan.little@iinteractive.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Builder: 0
  Test::Deep: 0
  Test::Exception: 0.21
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Path-Router
no_index:
  directory:
    - inc
    - t
requires:
  File::Spec::Unix: 0
  Moose: 0.74
  MooseX::Clone: 0.04
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
